# Define the local network alowed to use the proxy
acl localnet src 192.168.1.0/24
http_access allow localnet
http_access allow localhost
http_access deny all

# Proxy port
http_port 3128

# dedicated transparent interception port
http_port 3129 intercept

# Caching Optimization for Raspberry Pi
cache_mem 512 MB
maximum_object_size_in_memory 512 KB
cache_dir ufs /var/spool/squid 2000 16 256
maximum_object_size 100 MB


# Log locations inside the container
access_log daemon:/var/log/squid/access.log squid
