services:
  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./data:/data
    command: '--data-dir /data --api-key=rb2eurfjg0i5093k0efj0secretkey --enable-cors'