services:
  postgres:
    image: postgres:14.2
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=appdata
      - POSTGRES_DB=europarcs